version: "3.8"

services:
  edxp-app:
    container_name: edxp-app
    image: dxeng2022/dxeng-deploy
    entrypoint:
      - java
      - -jar
      - ./app.jar
    environment:
      - MAIL_SENDER_USERNAME=${MAIL_SENDER_USERNAME}
      - MAIL_SENDER_PASSWORD=${MAIL_SENDER_PASSWORD}
      - MODULE_PARSER_URL=${MODULE_PARSER_URL}
      - MODULE_ANALYZE_URL=${MODULE_ANALYZE_URL}
      - AWS_S3_URL=${AWS_S3_URL}
      - IAM_ACCESS_KEY=${IAM_ACCESS_KEY}
      - IAM_SECRET_KEY=${IAM_SECRET_KEY}
      - FILE_PATH=${FILE_PATH}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always