version: "3.8"

services:
  edxp-database:
    container_name: edxp-database
    build:
      dockerfile: Dockerfile
      context: dockerfiles/database
    image: epikeran/edxp-database
    environment:
      - MYSQL_DATABASE=edxp
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./dockerfiles/database/config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  edxp-app:
    container_name: edxp-app
    build:
      dockerfile: Dockerfile
      context: dockerfiles/app
    image: epikeran/edxp-app
    environment:
      - MAIL_SENDER_USERNAME=${MAIL_SENDER_USERNAME}
      - MAIL_SENDER_PASSWORD=${MAIL_SENDER_PASSWORD}
      - IAM_ACCESS_KEY=${IAM_ACCESS_KEY}
      - IAM_SECRET_KEY=${IAM_SECRET_KEY}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always